name: github-issue-2-jira
description: Allow your Github Issue to Jira automatically.
author: Atsushi Miyamoto
branding:
  icon: plus
  color: green
inputs:
  github_owner:
    description: "Github Owner"
    default: ""
    required: true
  github_repo:
    description: "Github Repository name"
    default: ""
    required: true
  github_token:
    description: "Github Token"
    default: ${{ github.token }}
    required: false
  jira_project_key:
    description: "Jira Project Key for sync"
    default: ""
    required: true
  jira_hostname:
    description: "Jira hostname for sync"
    default: ""
    required: true
  jira_auth_token:
    description: "Jira auto token for sync"
    default: ""
    required: true
  jira_issue_type:
    description: "Jira issueType to set jira ticket"
    default: "Bug"
    required: false
  synced_label:
    description: "Set this label if synced success"
    default: "workflow/synced"
    required: false
  accepted_label:
    description: "Sync if issue has set this label"
    default: "triage/accepted"
    required: false
  since:
    description: "Only fetch issues, based on updated time after the given time. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ."
    default: ""
    required: false
  per_page:
    description: "The number of fetch latest issues"
    default: "5"
    required: false
  github_issue_number:
    description: "The number of fetch latest issues"
    default: ${{ github.event.issue.number }}
    required: false
runs:
  using: "composite"
  steps:
    - run: go run ${{ github.action_path }}/main.go
      shell: bash
      env:
        INPUT_GITHUB_OWNER:     ${{ inputs.github_owner }}
        INPUT_GITHUB_REPO:      ${{ inputs.github_repo }}
        INPUT_GITHUB_TOKEN:     ${{ inputs.github_token }}
        INPUT_JIRA_PROJECT_KEY: ${{ inputs.jira_project_key }}
        INPUT_JIRA_HOSTNAME:    ${{ inputs.jira_hostname }}
        INPUT_JIRA_AUTH_TOKEN:  ${{ inputs.jira_auth_token }}
        INPUT_JIRA_ISSUE_TYPE:  ${{ inputs.jira_issue_type }}
        INPUT_SYNCED_LABEL:     ${{ inputs.synced_label }}
        INPUT_ACCEPTED_LABEL:   ${{ inputs.accepted_label }}
        INPUT_SINCE:            ${{ inputs.since }}
        INPUT_PER_PAGE:         ${{ inputs.per_page }}
        INPUT_GITHUB_ISSUE_NUMBER:         ${{ inputs.github_issue_number }}
