name: github-issue-sync-2-jira
description: Allow your Github Issue to Jira automatically.
author: Atsushi Miyamoto
branding:
  icon: plus
  color: green
inputs:
  github-owner:
    description: "Github Owner"
    default: ""
    required: true
  github-repo:
    description: "Github Repository name"
    default: ""
    required: true
  github-token:
    description: "Github Token to access issue"
    default: ""
    required: true
  github-issue-number:
    description: "Labeled issue"
    default: ${{ github.event.issue.number }}
    required: false
  jira-project-key:
    description: "Jira Target Project"
    default: ""
    required: true
  jira-hostname:
    description: "Jira hostname"
    default: ""
    required: true
  jira-auth-token:
    description: "Jira auth token for authentication."
    default: ""
    required: true
  jira-auth-email:
    description: "Jira user email for authentication."
    default: ""
    required: true
  jira-issue-type:
    description: "Jira issueType should be set for the Jira ticket."
    default: "Bug"
    required: false
  synced-label:
    description: "Apply this label upon successful synchronization."
    default: "workflow/synced"
    required: false
  accepted-label:
    description: "Synchronize if the issue has this label applied."
    default: "triage/accepted"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.x'
    - name: sync2jira     
      env:
        GITHUB_OWNER:         ${{ inputs.github-owner }}
        GITHUB_REPO:          ${{ inputs.github-repo }}
        GITHUB_TOKEN:         ${{ inputs.github-token }}
        GITHUB_ISSUE_NUMBER:  ${{ inputs.github-issue-number }}
        JIRA_PROJECT_KEY:     ${{ inputs.jira-project-key }}
        JIRA_HOSTNAME:        ${{ inputs.jira-hostname }}
        JIRA_AUTH_TOKEN:      ${{ inputs.jira-auth-token }}
        JIRA_AUTH_EMAIL:      ${{ inputs.jira-auth-email }}
        JIRA_ISSUE_TYPE:      ${{ inputs.jira-issue-type }}
        SYNCED_LABEL:         ${{ inputs.synced-label }}
        ACCEPTED_LABEL:       ${{ inputs.accepted-label }}
      run: |
        chmod +x ${{ github.action_path }}/build/go1.19/action
        ${{ github.action_path }}/build/go1.19/action
      shell: bash
