name: github-issue-2-jira
description: Allow your Github Issue to Jira automatically.
author: Atsushi Miyamoto
branding:
  icon: plus
  color: green
inputs:
  github_owner:
    description: "Github Owner"
    default: ""
    required: true
  github_repo:
    description: "Github Repository name"
    default: ""
    required: true
  github_token:
    description: "Github Token"
    default: ""
    required: true
  github_issue_number:
    description: "The labeled issue"
    default: ${{ github.event.issue.number }}
    required: false
  jira_project_key:
    description: "Jira Project Key for sync"
    default: ""
    required: true
  jira_hostname:
    description: "Jira hostname for sync"
    default: ""
    required: true
  jira_auth_token:
    description: "Jira auto token for sync"
    default: ""
    required: true
  jira_issue_type:
    description: "Jira issueType to set jira ticket"
    default: "Bug"
    required: false
  synced_label:
    description: "Set this label if synced success"
    default: "workflow/synced"
    required: false
  accepted_label:
    description: "Sync if issue has set this label"
    default: "triage/accepted"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        GITHUB_OWNER="${{ inputs.github_owner }}"
        GITHUB_REPO="${{ inputs.github_repo }}"
        GITHUB_TOKEN="${{ inputs.github_token }}"
        GITHUB_ISSUE_NUMBER="${{ inputs.github_issue_number }}"
        JIRA_PROJECT_KEY="${{ inputs.jira_project_key }}"
        JIRA_HOSTNAME="${{ inputs.jira_hostname }}"
        JIRA_AUTH_TOKEN="${{ inputs.jira_auth_token }}"
        JIRA_ISSUE_TYPE="${{ inputs.jira_issue_type }}"
        SYNCED_LABEL="${{ inputs.synced_label }}"
        ACCEPTED_LABEL="${{ inputs.accepted_label }}"
        echo "GITHUB_OWNER=${GITHUB_OWNER}" >> $GITHUB_ENV
        echo "GITHUB_REPO=${GITHUB_REPO}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
        echo "GITHUB_ISSUE_NUMBER=${GITHUB_ISSUE_NUMBER}" >> $GITHUB_ENV
        echo "JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}" >> $GITHUB_ENV
        echo "JIRA_HOSTNAME=${JIRA_HOSTNAME}" >> $GITHUB_ENV
        echo "JIRA_AUTH_TOKEN=${JIRA_AUTH_TOKEN}" >> $GITHUB_ENV
        echo "JIRA_ISSUE_TYPE=${JIRA_ISSUE_TYPE}" >> $GITHUB_ENV
        echo "SYNCED_LABEL=${SYNCED_LABEL}" >> $GITHUB_ENV
        echo "ACCEPTED_LABEL=${ACCEPTED_LABEL}" >> $GITHUB_ENV
        go run ${{ github.action_path }}/main.go
      shell: bash
